kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    metadata:
      name: config
    networking:
      serviceSubnet: 13.0.0.0/16
    imageRepository: registry.aliyuncs.com/google_containers
    nodeRegistration:
      kubeletExtraArgs:
        pod-infra-container-image: registry.aliyuncs.com/google_containers/pause:3.7
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: InitConfiguration
    metadata:
      name: config
    networking:
      serviceSubnet: 13.0.0.0/16
    imageRepository: registry.aliyuncs.com/google_containers
nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
